# ======================== Filebeat Configuration ========================

# Define where Filebeat should look for log files
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/app/**/*.log
      - /var/log/app/*.log
    
    # JSON parsing
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true
    json.expand_keys: true

# Processors to reduce noise
processors:
  - drop_fields:
      fields: ["agent", "ecs", "input", "log", "host"]
      ignore_missing: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "BankAdmin123"
  index: "bank-logs-%{+yyyy.MM.dd}"

setup.template.name: "bank-logs"
setup.template.pattern: "bank-logs-*"
setup.ilm.enabled: false

logging.level: debug