# Server
server.port=8082
spring.application.name=transaction-service

# Logging
logging.level.com.bank=INFO
logging.config=classpath:logback-spring.xml

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always